FROM node:6.11

RUN apt-get update \
  && apt-get --yes --force-yes install git curl wget libsnappy-dev autoconf automake libtool pkg-config

RUN git clone https://github.com/openvenues/libpostal \
  && cd libpostal \
  && ./bootstrap.sh \
  && mkdir /libpostal_data \
  && ./configure --datadir=/libpostal_data \
  && make \
  && make install \
  && ldconfig
