FROM chrissng/libpostal

RUN apt-get update \
  && apt-get --yes --force-yes install git curl wget unzip

ENV HOME /pelias
WORKDIR ${HOME}

# Download the Pelias repositories
COPY pull-pelias-repos.sh ./pull-pelias-repos.sh
RUN ./pull-pelias-repos.sh schema api geonames openaddresses openstreetmap

WORKDIR /rawdata

# Download the Singapore OSM extract
RUN mkdir -p ./openstreetmap \
  && wget -P ./openstreetmap http://download.geofabrik.de/europe/germany/baden-wuerttemberg-latest.osm.pbf

# Download the Singapore OpenAddresses
RUN mkdir -p ./openaddresses \
  && wget -P ./openaddresses $(curl -s http://results.openaddresses.io/?runs=all#runs | grep '/de/nw/statewide.zip' | grep -Po '(?<=href=")[^"]*(?=")') \
  && unzip -d ./openaddresses ./openaddresses/countrywide.zip

# Download the Singapore GeoNames
RUN mkdir -p ./geonames \
  && wget -P ./geonames http://download.geonames.org/export/dump/DE.zip

# Set the configuration file
COPY pelias.json ${HOME}/pelias.json

# Entry point to start Pelias
WORKDIR ${HOME}
COPY entrypoint.sh ./entrypoint.sh
ENTRYPOINT ./entrypoint.sh
