version: '2'
services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile-elasticsearch
    container_name: pelias_elasticsearch
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    restart: always
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/logs:/usr/share/elasticsearch/logs
  pelias:
    build:
      context: .
      dockerfile: Dockerfile-pelias
    container_name: pelias
    image: chrissng/pelias
    ports:
      - 3100:3100
    restart: always
    depends_on:
      - elasticsearch
    volumes_from:
      - elasticsearch:ro
